# -*- coding: utf-8 -*-
"""Manipulação de Arrays

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wf9GWX1lVVAWVPtywYmBb3fx1UOBqla_
"""

#Declarando lista de produtos
lista_produtos = ['máscaras faciais', 'batons', 'esmaltes', 'perfumes', 'loções', 'xampus', 'sabonetes', 'delineadores']
print("Lista carregada")

# Verifica se o item existe na lista e substitui pelo que você quer
def alterarItem(lista, find, change):
    for i in range(len(lista)):
        if lista[i] == find:
            lista[i] = change

#Remover item da lista
def removerItem(lista, item_a_remover):
  for item in lista:
    if item == item_a_remover:
      lista.remove(item_a_remover)

print("Funções carregadas")

# Alterando os itens da lista pelos que eu quero
print("Lista Original: ", lista_produtos)
alterarItem(lista_produtos, 'batons', 'rímel')
alterarItem(lista_produtos, 'loções', 'cremes hidratantes')
print("Lista Modificada: ", lista_produtos)

# Remover item da lista
removerItem(lista_produtos, 'delineadores')

# Adicionando 2 itens no array
lista_produtos.append('ARROZ')
lista_produtos.append('FEIJÃO')
print(lista_produtos)

for i in range(len(lista_produtos)):
  print(f"Temos {lista_produtos[i]} à venda!")